# This is a basic workflow to help you get started with Actions

name: CI-artifact

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  watch:
    types: [started]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: |
        echo "GITHUB_RUN_ID: $GITHUB_RUN_ID"
        echo "GITHUB_RUN_NUMBER: $GITHUB_RUN_NUMBER"
        echo "GITHUB_SHA: $GITHUB_SHA"
        echo "GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH"

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        mkdir output
        cp *.md output
        
  
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: docs
    # Directory containing files to upload
        path: output
        
    - name: upload2
      uses: actions/upload-artifact@v2-preview
      id: upload2
      with:
       name: docs1
       path: output
    
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    
    - name: Dump steps context
      env:
       STEPS_CONTEXT: ${{ toJson(steps.upload2.outputs) }}
      run: echo "$STEPS_CONTEXT"
